name: Keep Codespace Alive
on:
  schedule:
    - cron: "*/1 * * * *"  # Runs every 15 minutes

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Make Request
        run: |
          curl -I "https://github.com/k8ngsparklr/tesop/actions/runs/11709139140"
